//
// Created by ivenpoker on 7/15/22.
//

#ifndef PLATFORM_W3RESOURCE_BASIC_DECLARATIONS_AND_EXPRESSIONS_EXERCISE_12_LINE_UTIL_P_H
#define PLATFORM_W3RESOURCE_BASIC_DECLARATIONS_AND_EXPRESSIONS_EXERCISE_12_LINE_UTIL_P_H

#include <stdbool.h>

bool isInRange(int lower, int val, int upper);
bool isNotInRange(int lower, int val, int upper);

#endif //PLATFORM_W3RESOURCE_BASIC_DECLARATIONS_AND_EXPRESSIONS_EXERCISE_12_LINE_UTIL_P_H
