//
// Created by ivenpoker on 7/15/22.
//

#ifndef PLATFORM_W3RESOURCE_BASIC_DECLARATIONS_AND_EXPRESSIONS_EXERCISE_13_INPUT_H
#define PLATFORM_W3RESOURCE_BASIC_DECLARATIONS_AND_EXPRESSIONS_EXERCISE_13_INPUT_H

typedef char * string_t;
typedef const char * string_ct;

int retrieveInput(string_ct message);

#endif //PLATFORM_W3RESOURCE_BASIC_DECLARATIONS_AND_EXPRESSIONS_EXERCISE_13_INPUT_H
